# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gector's Box
email: gector@fastmail.com
description: > # this means to ignore newlines until "baseurl:"
        A box of random junk lies on the floor in the north-west corner of the room, the text "gector's box" is written on the box.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  captaingector

# Build settings
markdown: kramdown
